### PR TITLE
Introduction of Github Actions

### LINKED ISSUE #180: Add an automatic version number
Wouldn't it be nice if the script showed the version number when it ran? It would make user troubleshooting easier - and our own!

It would also be nice to integrate the version number properly when we start on a proper package deployment. 

I've started [the branch "version-numbering"](https://github.com/torbengb/bank2ynab/tree/version-numbering) to try to work on this.

I've now made code that works in Py2, but oddly Travis complains about Py3 while I can't reproduce that.

My version construction might seem a little roundabout, but I've integrated existing packages that are made for this purpose. 

- [ ] TODO: make the code pick up the version from the Git tag.

On top of that, I've added the basis of a version suffix so that we can see what branch the code came from. On the `master` branch, no suffix should be shown.

- [ ] TODO: make the code pick up the branch, and add it as suffix.

Further tasks to complete the proper configuration of `setup.py`:

- [x] rearrange the file structure according to [this guide](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html#arranging-your-file-and-directory-structure).
- [ ] rename our `README.md` into `.srt` format as suggested in the same link.
- [x] note I started writing [this wiki page](https://github.com/torbengb/bank2ynab/wiki/PublishRelease) about details of the process.

### LINKED ISSUE #238: Create version-numbering Github Action
**Is your feature request related to a problem? Please describe.**
The script should display the current version number when running, e.g. bank2ynab v1.1.0

**Describe the solution you'd like**
A pre-commit hook to obtain the number from the git tag is the way to do it...I think!

**Describe alternatives you've considered**
I'll leave this one in @torbengb's court, as I don't really understand the git tag side of things currently.

### LINKED ISSUE #258: Increased project automation (Github Actions)
**Other feature request**

**Is your feature request related to a problem? Please describe.**
The following issues all reference using hooks to automate certain aspects of the development workflow: #239, #238, #181. 

After doing some research, I think the best way to approach these tasks is to actually make use of the deployment abilities of Travis rather than using hooks.

**Describe the solution you'd like**
Let's give Travis superpowers! Essentially, we need to add a "deployment" phase to Travis that occurs after a successful round of testing. This could, for example, do the following tasks.
- Bump the version number for every commit to the `master` branch
- Update `README.md` every time a new bank is added to the config
- Automatically fix formatting issues from new commits
- Automatically deploy new versions of the `master` branch to PyPi

We'll need to somehow give Travis an authorisation key, this will be the trickiest part, I think, as it will need to be kept secure. Travis has documentation on encryption, linked below, which will probably be helpful.

**Describe alternatives you've considered**
Either continue to do these tasks manually or use the hooks concept. The problem with the hooks is that these are finicky to install and update. Travis provides a centralised solution. 

**Additional context**
***Travis Docs***
Github Releases uploading: https://docs.travis-ci.com/user/deployment/releases/
PyPi Deployment: https://docs.travis-ci.com/user/deployment/pypi/
Encryption Keys: https://docs.travis-ci.com/user/encryption-keys/

### LINKED ISSUE #307: GitHub "Actions"? -->
**Is your feature request related to a problem? Please describe.**
GitHub has added a new kind of thing that apparently automates the Python packaging process?   
https://github.com/bank2ynab/bank2ynab/actions/new

**Describe the solution you'd like**
We should look into how we could leverage that for this project.
I'll put it on my list and see when I get around to it.

### LINKED ISSUE #309: Replace Travis with Github Actions
**Other feature request**

**Is your feature request related to a problem? Please describe.**
Github Actions are more tightly integrated into Github and offer some interesting workflow options. 

**Describe the solution you'd like**
I think we should migrate our Travis testing into Github Actions.

**Describe alternatives you've considered**
We could leave Travis running on his own, but the fewer moving parts this project has, the better.

**Additional context**
#307 and branch #308

### PR DESCRIPTION
**Pull request by nocalla**
**Reference Issue:**
Several different automation-related issues. Referenced below in the changes list.

**Description**
Github actions and workflows look like a powerful way for us to organise this repo. Experimentation underway!

**Implemented**
- Introduction of Github Actions workflows and general automation (Fixes #307 and fixes #258 )
- Replace `Travis` with a set of workflows (Fixes #309 )
- Add automatic linting `codestyle.yml` which automatically fixes code style issues using `black` (Fixes #258 )
- Bump the version number for every commit to the `master` branch (Fixes #238 and Fixes #180 )
- Automatically make new release for every commit to `master`

**In Progress**
- Introduce `labeler` workflow to automatically label pull requests based on files changed 
    - Needs more label options than just `meta`

**To-Do**

- Update `README.md` every time a new bank is added to the config #239 
- Automatically deploy new versions of the `master` branch to PyPi #176
- Code coverage testing

### CODE REVIEW

**Comment by nocalla** [comment]
So the checks work, which is very cool!

**Comment by torbengb** [comment]
Man, talk about taking the ball and running with it! This is impressive!

**Comment by nocalla** [comment]
I think your package project is very do-able with these actions, they're very versatile.

**Comment by nocalla** [comment]
Hey @torbengb - I added a thing that automatically fixes code style issues on commit! Hooray for robots!

**Pull request merged**
