### PR TITLE
Plugin for Raiffeisen RCM format

### LINKED ISSUE #269: plugin-RaiffeisenRCM returns error 400
**Describe the bug**
1. I have created the branch `plugin-RaiffeisenRCM` which contains a plugin to read the Raiffeisen-proprietary file format `RCM`. 
1. This plugin includes currency conversion from legacy ATS to EUR using a fixed currency conversion rate. It is correct to use a fixed currency conversion rate; this is part of the RCM format definition.
1. Bank format + plugin + test data is provided in the branch.

**What did you EXPECT to happen?**
Successful upload and import into YNAB.

**What ACTUALLY happened?**
1. When executed, the program correctly reads and parses the input file. 
1. It also correctly generates the output file -- except that **it does not have the YNAB header row**.
1. The program then tries to upload this file to the YNAB API but we get an error:
```
INFO: Uploading transactions to YNAB...
INFO: Starting new HTTPS connection (1): api.youneedabudget.com
ERROR: 400 - Bad syntax or validation error (bad_request)
```

**What did you DO? (steps to reproduce)**
1. Run the program with a sample RCM file (see sample file in directory "test-data").
2. Error 400 occurs.

**What's your software environment?**
 - Script language: Python 3.5
 - Operating system: Linux
 - OS version: Ubuntu 16.04 LTS

**Can you provide other helpful information?**
It seems to me that I am missing something in the plugin to make it generate the YNAB header row, but I can't see what's missing. I have compared my plugin with the other two plugins but didn't see anything obvious. 

**Attachments**
See branch [`plugin-RaiffeisenRCM`](https://github.com/bank2ynab/bank2ynab/tree/plugin-RaiffeisenRCM) for sample files.

**Proposed Config**
```
[AT Raiffeisen Bank RCM]
Source Filename Pattern = kta_ei
Source Filename Extension = .dat
Source CSV Delimiter = |
Input Columns = skip,Memo,Date,Payee,Inflow,Memo
Date Format = %Y%m%d
Plugin = RaiffeisenRCM
```

**Sample Data**
```
K|32000|244081|EUR
| POS 6,49 AT K1 09.03. 09:53|20190311|FORSTINGER |-89.30|
| POS 7,96 AT K1 09.03. 10:15|20190311|DER MANN - BACKWAREN|-109.53|
| POS 49,90 AT K2 09.03. 13:04|20190311|BIPA WIEN 1210|-686.64|
| POS 12,87 AT K2 09.03. 13:43|20190311|KIK AUSTRIA FIL. 3220|-177.10|
| HOFER DANKT 0551 K2 09.03. 14:01|20190311| |-983.59|
| SEPA Lastschrift|20190311| Zahlungsempfänger:  S.C.D.|-227.73| Empfänger-Kennung:  LU96KKE12
| POS 4,50 AT K2 09.03. 12:50|20190311|C&A STORE|-61.92|
| SEPA Lastschrift|20190312| Zahlungsempfänger:  John Doe|-2015.88| Empfänger-Kennung:  AT01ZZZ00000123
| ONLINE BANKING VOM 12.03 UM 12:00|20190312| Empfänger:  Dingbats|-1492.99| Verwendungszweck:  09914469
| POS 9,95 AT K2 12.03. 16:08|20190313|DEICHMANN GMBH|-136.91|
| POS 12,40 AT K2 13.03. 13:58|20190313|MCFLY|-170.63|
```

### PR DESCRIPTION
**Pull request by torbengb**
**New Pull Request**

**Reference Issue:**
I resolved #269 - the file can be manually imported into YNAB so it will now also work via the API.

**Description**
This implements Raiffeisen Bank's proprietary export format. It's more useful than their CSV because it includes more payee and memo information.

### CODE REVIEW

**Comment by torbengb** [comment]
Ah, the file "RaiffeisenRCM-debug.py" should be removed. That'll be another day - good night!

**Comment by nocalla** [comment]
I'm going to include instructions on "pre-commit" soon. It's an automatic package that can auto fix formatting errors like the ones Travis is complaining about here.

**Comment by torbengb** [comment]
Travis:

- The build fails but I don't see any reason given so I can't determine what steps are required.

codeclimate: 

- I am trying to fix those failed checks, but I am stumped at the issues of "Cognitive Complexity" and "Cyclomatic complexity". I don't see that there's anything I can do to reduce those scores.

**Comment by nocalla** [comment]
It's a formatting issue. You need two empty lines at line 69.

Don't worry too much about code climate- those are more complex fixes!

**Pull request merged**
