### PR TITLE
Add payee transformation function

### LINKED ISSUE #404: Transformation map for payee names
**Other feature request**

**Is your feature request related to a problem? Please describe.**

Hey all, I am already a big fan of this script. Thanks.

One problem... let's call it nuisance... I came across is the fact that many of my recurring payees have names like "PAYPAL (EUROPE) S.A.R.L ET CIE,S.C.A." which I would like to rename. Is this a feature you would accept a Pull Request for? A decision I need your guidance with would certainly be where to provide this transformation list. Is a new section in `user_configuration.conf` okay with you or will it collide with the banks?

(Btw ever consider to transition the config files to yaml?)

### PR DESCRIPTION
**Pull request by ThomDietrich**
Resolves #404

### CODE REVIEW

**Comment by ThomDietrich** [comment]
This did a good job importing-exporting 280 transactions

**Comment by raiviskrumins** [comment]
This is crucial functionality for me, thank you for this.
As an additional "feature", it would be awesome if this supported regex
One of our retailers is "Rimi", and depending on store location I get different Payees:
```
[Payee]
; Rimi
RIMI HM MOLS\KRASTA IELA 46\RIGA\LV-1003      LVA = Rimi
RIMI CHM VALDEMARA (RI\KR. VALDEMARA IELA 112\RIGA\LV-1013      LVA = Rimi
RIMI LHM ALFA (RIGA)\BRIVIBAS GATVE 372\RIGA\LV-1006      LVA = Rimi
RIMI CHM Saga (Stopini\Bikeru iela 4\DREILINI\LV-2130      LVA = Rimi
...and many more
```
if I could use regex like this, it would match all of these
```
[Payee]
; Rimi
^RIMI.* = Rimi
```

**Comment by ThomDietrich** [comment]
Hey @raiviskrumins,
that makes sense to me. The solution would probably be simple, however it is not possible atm, because the configuration file with its `ini` format is quite restricted. Regex expressions as the key will not be parsed correctly. @nocalla another reason why to switch to yaml for all configuration.

**Comment by nocalla** [comment]
> Regex expressions as the key will not be parsed correctly. @nocalla another reason why to switch to yaml for all configuration.

Regex is already supported in the configuration file for file names.

**Pull request closed without merging**
