### PR TITLE
Update Master branch for feature parity with Develop

### PR DESCRIPTION
**Pull request by nocalla**
**New Pull Request**

**Reference Issue:**
#298 

**Description**
The above-referenced issue highlighted that our `master` branch is throwing Syntax Warnings, so I think we are well-overdue an update to the `master`.

*Explain the changes that this pull request makes*
Oh man, there's a lot, we have *not* been diligent with updating the `master`!

### CODE REVIEW

**Comment by nocalla** [comment]
The main changes are the addition of the YNAB API and more supported banks.

**Comment by nocalla** [comment]
I'm going ahead with the LONG overdue master merge. No doubt something will break, but let's see what happens.

**Comment by torbengb** [comment]
Thank you @nocalla for picking this up! Remember we have this wiki step-by-step page for the publishing process: https://support.youneedabudget.com/t/x1rpy9/no-payee-matching-for-api-created-transactions

**Comment by torbengb** [comment]
(fixed incorrect [wiki link](https://github.com/bank2ynab/bank2ynab/wiki/PublishRelease).)

**Comment by torbengb** [comment]
Seeing that this was already merged (yay!) I've now tagged the master and added it as a new official release, including a small blurb in the way of release notes.
https://github.com/bank2ynab/bank2ynab/releases/tag/1.2.0

**Pull request merged**
