### PR TITLE
Add support for [CO] Bancolombia

### LINKED ISSUE #106: Support for Bancolombia [CO]
Sourced from [Asgaroth/ynab](https://github.com/Asgaroth/ynab).

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

From Issue #21 master list

### PR DESCRIPTION
**Pull request by nocalla**
**Reference Issue:**
Fixes #106 

**Description**
Adds bank format information provided by @ricardopolo

```
[CO Bancolombia]
Source Filename Pattern = [0-9]{3}-[0-9]{6}-[0-9]{2}_[0-9]{3}
Source Filename Extension = .txt
Use Regex for Filename = True
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Memo,Inflow
```

### CODE REVIEW

**Comment by ricardopolo** [comment]
I don't think the columns are ok, please refer to my comment in #106

**Comment by nocalla** [comment]
Can you test this branch @ricardopolo and see if it properly converts your file?

**Comment by ricardopolo** [comment]
I will test it in on the weekend

**Comment by ricardopolo** [comment]
I did it. I get this result. Is it ok?
image

Where is the file located after processing to upload in the web app?

**Comment by ricardopolo** [comment]
Any idea?

**Comment by nocalla** [comment]
Hi @ricardopolo - the date format was missing from the format so the file wasn't read correctly. I've updated the format so this should be fixed - please try again and let me know.

 The output file will be in the same folder as the original.

**Comment by ricardopolo** [comment]
Great, it works now. Thanks! 
image

**Comment by nocalla** [comment]
Great, thanks for your help.

**Comment by ricardopolo** [comment]
Thanks to you

**Pull request merged**
