### PR TITLE
BETA: Added support for sparekassen thy temp filename: thyposteringer

### PR DESCRIPTION
**Pull request by duch11**
Still need to know what the default filename is for sparekassen thy.
Don't know if that qualifies for a pullrequest however.. thanks

Issue reference: #219

### CODE REVIEW

**Comment by nocalla** [comment]
Well if we don't have the filename, the script won't find the file for the
bank, so it won't do anything.

**Comment by simzdk** [comment]
Filnavn er: export.csv

**Comment by duch11** [comment]
It should be good for importing now. 
Check it out @simzdk does it work?

**Comment by simzdk** [comment]
Not work. Found out I made an error. The delimter should be ";". So a line is: 
"09-10-2018";"09-10-2018";"Tøj";"-526,00";"2.133,02"

I change this in the config, but 0 files are processed.

**Comment by duch11** [comment]
`ValueError: time data '09-10-2018;"09-10-2018";"MobilePay køb WeShare";"-231' does not match format '%Y-%m-%d'`
It seems it's not recognizing the delimiter..

**Comment by nocalla** [comment]
@simzdk can you paste the current config you're using?

**Comment by simzdk** [comment]
> @simzdk can you paste the current config you're using?

[DK Sparkassen Thy]
Source Filename Pattern = export
Source CSV Delimiter = ;
Header Rows = 0
Input Columns = skip,Date,Payee,Inflow,Running Balance

I suspect it might be because of "" around all numbers?

**Comment by nocalla** [comment]
Are there quotation marks around the numbers in the files from other banks, @duch11?

**Comment by duch11** [comment]
Nope not from my bank at least:
`11-10-2018;"Forretning: Transferwise";-102,40; 300,27;`

**Comment by simzdk** [comment]
> Nope not from my bank at least:
> `11-10-2018;"Forretning: Transferwise";-102,40; 300,27;`
> however, when I tested your file, I hadn't any problems..
> Can you give an exact dump of a export.csv @simzdk ?
> 
> > Not working. Found out I made an error. The delimter should be ";". So a line is:
> > "09-10-2018";"09-10-2018";"Tøj";"-526,00";"2.133,02"
> 
> Is this an exact dump?

This is a bigger export. Only changes made are the running balance. 
"11-10-2018";"11-10-2018";"kontaktløs Dankort Føtex";"-248,92";"600"
"10-10-2018";"10-10-2018";"kontaktløs Dankort Føtex";"-44,00";"700"
"09-10-2018";"09-10-2018";"kontaktløs Dankort Føtex";"-78,10";"800"
"08-10-2018";"08-10-2018";"kontaktløs Dankort Fakta 12";"-27,00";"1000"
"08-10-2018";"08-10-2018";"kontaktløs Dankort Rema 1000II";"-560,70";"1100"
"08-10-2018";"08-10-2018";"kontaktløs Dankort MENY";"-110,90";"1200"

**Comment by nocalla** [comment]
No actually, I don't think so. It hasn't come up!

**Comment by nocalla** [comment]
I'm merging this into a branch on the main repo so that our automated tests will work better. I'll reference the new Pull Request below.

**Pull request merged**
