### PR TITLE
Feature/sparekassen thy

### PR DESCRIPTION
**Pull request by nocalla**
Issue reference #219 

Merged from Pull Request #223

### CODE REVIEW

**Comment by nocalla** [comment]
@duch11 @simzdk

So I don't think the error is down to quotation marks in the inflow/outflow. So here's what the script reads a row in the test data file for BOI as:

['01/09/2017', 'Random Name      GP', '', '428.03', '100']

By contrast, here's what it reads this test file's rows as:
['11-10-2018;"11-10-2018";"kontaktløs Dankort Føtex";"-248', '92";"600"']

For some reason, the entirety of the row is enclosed within single quotation marks, so it just sees a single entry in the row.

**Comment by nocalla** [comment]
I had a hypothesis that the wrong bank format was being used to parse the file. Alas, this isn't the case.

**Comment by nocalla** [comment]
Found the error - the delimiter was still a comma instead of a semi-colon! The config was never updated.

**Comment by simzdk** [comment]
But the config I manually made I use the semi colon. How do I pull the develop branch to test?

**Comment by nocalla** [comment]
That depends on your set-up, but there should be a download button on the front page if you just want to download it manually.

**Pull request merged**
