### PR TITLE
181_Pre-commit hooks

### LINKED ISSUE #181: How do I add a pre-commit hook?
it should go into the file:
bank2ynab/.git/hooks/pre-commit but when I added that, it ended up as:
bank2ynab/hooks/pre-commit

### LINKED ISSUE #235: Add documentation on how to work with pre-commit hooks
Add documentation on how to work with pre-commit hooks.

### LINKED ISSUE #236: Add documentation explaining how to set up dev environment
Add documentation explaining how to set up dev environment. 

Must cover:
    - Symbolic link to hooks folder (not strictly necessary any more, I think?)
    - Installation of requirements-dev.txt

### LINKED ISSUE #237: Add comments to pre-commit hook config file explaining each hook

### LINKED ISSUE #238: Create version-numbering Github Action
**Is your feature request related to a problem? Please describe.**
The script should display the current version number when running, e.g. bank2ynab v1.1.0

**Describe the solution you'd like**
A pre-commit hook to obtain the number from the git tag is the way to do it...I think!

**Describe alternatives you've considered**
I'll leave this one in @torbengb's court, as I don't really understand the git tag side of things currently.

### LINKED ISSUE #239: [Github Action] Auto update list of supported banks in README based on bank2ynab.conf
**Is your feature request related to a problem? Please describe.**
It's annoying having to enter new banks in the README file after entering them into the config file

**Describe the solution you'd like**
Automatically read the config file to get the section names, then write these to the README file

**Describe alternatives you've considered**
This might not even be feasible...further investigation needed!

### LINKED ISSUE #240: Use Black instead of Autopep8 for pre-commit hook (an investigation)
**Is your feature request related to a problem? Please describe.**
Black is apparently a big help in making readable code, it might be worth trying instead of autopep8

**Describe the solution you'd like**
Replace autopep8 with black in the pre-commit config file

**Describe alternatives you've considered**
Leave autopep8 in place instead in case Black is awful!

### PR DESCRIPTION
**Pull request by nocalla**
**New Pull Request: Hook, line, and sinker!**

**Reference Issue:**
Originally inspired by #181 but other issues listed below

**Description**
Adds pre-commit functionality to trigger scripts when committing to the repo, allowing auto-formatting to take place and preventing different standards from messing with readability!

- [x] Create pre-commit hook functionality (fixes #181)
- [x] Add requirements-dev.txt - this will allow us to state which tools are needed for development
- [x] Add [pre-commit](https://pre-commit.com/) as a dev requirement
- [x] Add .pre-commit-config.yaml to configure which hooks to run
- [x] ~~Maybe use Black instead of autopep8 for maximum readability? I must experiment with this and see how extreme it is!~~ (won't fix - requires Python 3.6+. Closes #240)
- [x] Add comments to config file explaining each hook (fixes #237)

**To-Do**
- [ ] Add documentation explaining how to add hooks (fixes #235)
- [ ] Add documentation explaining how to set up dev environment (fixes #236)
    Covering:
    - ~~Symbolic link to hooks folder~~ (not needed with the pre-commit package)
    - Installation of requirements-dev.txt
- [ ] Create hook to do whatever it was @torbengb wants to do with version numbering! (fixes #238)
- [ ] Create hook to scan our config file and add supported banks to the README (fixes #239)

### CODE REVIEW

**Comment by nocalla** [comment]
@torbengb, can you comment here with *exactly* what you want a hook to do with version numbering? I'm not exactly sure how to make locally-defined hooks work across all platforms, but I'll see what I can do.

**Comment by torbengb** [comment]
> _exactly_ what you want a hook to do with version numbering

Yes, let me dig that out and comment here. Probably won't be today though!

**Comment by nocalla** [comment]
I've created an issue over on #238 so you can list out the steps needed.

**Comment by nocalla** [comment]
#258 will make this obsolete. Suspending work on this for the moment.

**Pull request closed without merging**
